### PR TITLE
New functions to expose Errors from Connection Pool and LetterId from RabbitService

### PR DESCRIPTION
**Pull request by jing-li-rocos**
Hi, this is a great RabbitMQ library, we are looking at deploying it to production.

Meanwhile, we have a scenario which requires to extend your library to support synchronized publish with confirmation. We plan to do the extension at our side first. However, we need 2 additional public functions from Connection Pool and Rabbit Service. 

- ConnectionPool.Errors() to expose the error raised internally to support logging and tracing
- RabbitService.GetNewLetterID() to expose the letter id counter for external extension methods but also keep the letter id logic within the RabbitService to keep the id synced all the time.

### CODE REVIEW

**Comment by houseofcat** [comment]
CorrelationId == Metadata, put whatever extra Identifier i.e. CorrelationID in the Metadata field. It would also break backwards compatibility.

It can be added to the Envelope as it is not there.

The ConnectionPool will need some thinking to be able to provide an alternative ConnectionPool that collects errors. As if any current user would not be subscribed to an ever increasing channel and thus have a memory leak.

**Comment by jing-li-rocos** [comment]
Ah, I am so sorry. I pushed other commits into our fork and forgot the PR was still on. Let me fix this.

**Comment by houseofcat** [comment]
I will provide an ErrorHandler ConnectionPool if you still need it, I can see the value there for visibility reasons.

**Comment by jing-li-rocos** [comment]
> I will provide an ErrorHandler ConnectionPool if you still need it, I can see the value there for visibility reason

Thanks so much, we do need it.

**Pull request closed without merging**
